// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaHiimBuYUu1-q3AeCUUdZ3Br5jgQSP0k',
    appId: '1:245592174525:web:7f5ac22c0e8c1c1e6dacd4',
    messagingSenderId: '245592174525',
    projectId: 'meald-36439',
    authDomain: 'meald-36439.firebaseapp.com',
    storageBucket: 'meald-36439.appspot.com',
    measurementId: 'G-N4T14L4Q60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAXjo724YOt7QJ9FtunQ6LCbGJ2gLtTsk',
    appId: '1:245592174525:android:4261c7e60acbf9a06dacd4',
    messagingSenderId: '245592174525',
    projectId: 'meald-36439',
    storageBucket: 'meald-36439.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnZw7LlSRvDW33ANd54DZaS81tC_6B8Fo',
    appId: '1:245592174525:ios:04961bc4b0a0268f6dacd4',
    messagingSenderId: '245592174525',
    projectId: 'meald-36439',
    storageBucket: 'meald-36439.appspot.com',
    iosBundleId: 'com.example.mealedProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnZw7LlSRvDW33ANd54DZaS81tC_6B8Fo',
    appId: '1:245592174525:ios:04961bc4b0a0268f6dacd4',
    messagingSenderId: '245592174525',
    projectId: 'meald-36439',
    storageBucket: 'meald-36439.appspot.com',
    iosBundleId: 'com.example.mealedProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaHiimBuYUu1-q3AeCUUdZ3Br5jgQSP0k',
    appId: '1:245592174525:web:0f0cfbc1078667af6dacd4',
    messagingSenderId: '245592174525',
    projectId: 'meald-36439',
    authDomain: 'meald-36439.firebaseapp.com',
    storageBucket: 'meald-36439.appspot.com',
    measurementId: 'G-ETPY6NYQVS',
  );
}
